* Meal Planning Basics

#+BEGIN_QUOTE
Without a strategy and a plan, a goal is no more than a dream.
#+END_QUOTE

#+BEGIN_QUOTE
Create the body of your dreams while still eating your fafourite food.
#+END_QUOTE

#+BEGIN_QUOTE
Your goals might be to lose weight, to gain weight, to lose fat or to gain muscle, or simply live a healthy life. 
Whatever your goals might be, Nutrimium is meant to help you to reach your goals.
#+END_QUOTE


** Meal Planning Explained

The most important principles in dieting and nutrition are (by order of importance decreasing):
1. *Calorie Balance* (= How Much You Eat)
2. *Macronutrient Amounts* (= What You Eat => Protein, Carbs, Fats)
3. Nutrient Timing (= When You Eat)
4. Food Composition
5. Supplements


** Calories explained

*** A calorie

Energy needed to raise temperature of 1 litre of water by 1 degree Celsius. 

A calorie = form of energy measurement.

When you eat food, you consume the energy that stored within the food.

*Energy can be stored for ater use (as glycogen or fat)*

*** Calorie Balance

3 different states of calorie balance. 

You can only be in ONE state at a time:

- Negative calorie balance => will result in weight loss
- Neutral calorie balance => no change in the weight
- Positive calorie balance => weight gain

The calorie balance will determine how much you can gain/lose over any given period of time.
Because the calories are the building blocks of body tissues.



** Macronutrients Explained

You body needs each of the 3 macronutrients in relatively large quantities to function properly. 

*** Proteins

Proteins helps with... 
- Producing antibodies for the immune system
- Manufacturing hormones
- Aiding in the digestion and absorption of food
- Maximizing the transport of oxygen to the tissues
- Providing structure for muscles, tendons, ligaments, organs, bones, hair, etc.

**** What happens when you consume proteins 

90% of the proteins you eat is broken down into amino acids
=> becomes part of the amino acid 'pool' that your body draws upon when it needs to build or 
 repair a muscle or any other tissue. 

Amino acids have no form of storage in the body so it's important to have some proteins every day. 

***** Amino Acids

= building blocks of protein

Necessary to support muscle growth

Divided into two subgroups: essential and non essential: 
- Essential (body cannot create them) => must be obtained from food or supplementation
- Non essential (body can create them)


*** Complete and Incomplete Proteins
- Complete protein: offers all essential amino acids
- Incomplete protein: missing one or more essential amino acids

- All animal proteins are complete proteins
- Plant-based proteins are generally incomplete


**** Tip for Vegans

To get all the essential amino acids make sure to get protein from a variety of sources

This compensate the lack of specific amino acids in specific foods

Consume a balanced diet including grains, vegetables and legumes, nuts and seeds.


*** How much protein do you need 

Ideal protein intake will depend on factors such as weight, muscle mass and fitness goals.

**** Optimal Daily Protein Intake

- To live a healthy life: 0.5 - 0.7 grams per pound of bodyweight
- To build muscle: 0.8 - 1 gram per pound of bodyweight
- To lose fat and maintain muscle: 0.8 - 1 gram per pound of bodyweight


*** Carbohydrates

The bodies preffered energy source. More specifically, carbs are sugar molecules that are a union 
of carbon, hydrogen and oxygen (CHO). Your body breaks carbs down into glucose, which is transported 
throughout the body to provide energy.

Any glucose not used is stored in your liver and muscles as glycogen or as fat.

**** Benefits of Cabs

- During high intensity activities your body uses glycogen and converts it back to glucose for new fuel. 
- Supply the nervous system with fuel => more concentration, more fatigue resistance and more motivation
- Reflueling glycogen stores
- Secreting insulin => helps tissues to grow

**** Types of Carbs

*** Dietary fats

Your body needs fatty acids to survive and cannot produce them from other foods.

Fat is needed to regulate hormone production, keep your skin and hair healthy, and
to absorb vitamins A, D, E and K (fat-soluble vitamins).

Fat cells insulate your body and help to keep you warm.

**** Types of Fat
There are two main types of fat:

- *Saturated fats* (eg. butter, cheese, whole milk) were long believed to raise LDL cholesterol level,
however recent studies suggest it's a lot less problematic. They are solid at room temperature.

- *Unsaturated fats* lower your LDL cholesterol level (include olive and canola oil, safflower, sunflower,
corn and soy oil).

There are also other types like *Trans fats*: form when vegetables oil is 
infused with hydrogen => avoid (eg. oil, butter and margarine) !


**** How much fat should you consume

Ideal Daily Fat Intake:
- 0.3 grams per pound of fat-free mass per day
- roughly 15 to 20% of daily calories 
- limit saturated fat intake, avoid artificial trans fats, and favor monounsaturated and polyunsaturated fats (unsaturated).

**** When to increase fat intake 

When all carbohydrates, fat and protein needs are already met, but your daily calories are not yet filled 
you have a choice to make => more proteinm fat or carbs?

In many cases, adding fat is good option because of:
- Taste
- Health effects
- Calorie density (9 cals vs 4) => ease of consumption
- Cost effectiveness
