* Meal Planning Basics

#+BEGIN_QUOTE
Without a strategy and a plan, a goal is no more than a dream.
#+END_QUOTE

#+BEGIN_QUOTE
Create the body of your dreams while still eating your fafourite food.
#+END_QUOTE

#+BEGIN_QUOTE
Your goals might be to lose weight, to gain weight, to lose fat or to gain muscle, or simply live a healthy life. 
Whatever your goals might be, Nutrimium is meant to help you to reach your goals.
#+END_QUOTE


** Meal Planning Explained

The most important principles in dieting and nutrition are (by order of importance decreasing):
1. *Calorie Balance* (= How Much You Eat)
2. *Macronutrient Amounts* (= What You Eat => Protein, Carbs, Fats)
3. Nutrient Timing (= When You Eat)
4. Food Composition
5. Supplements


** Calories explained

*** A calorie

Energy needed to raise temperature of 1 litre of water by 1 degree Celsius. 

A calorie = form of energy measurement.

When you eat food, you consume the energy that stored within the food.

*Energy can be stored for ater use (as glycogen or fat)*

*** Calorie Balance

3 different states of calorie balance. 

You can only be in ONE state at a time:

- Negative calorie balance => will result in weight loss
- Neutral calorie balance => no change in the weight
- Positive calorie balance => weight gain

The calorie balance will determine how much you can gain/lose over any given period of time.
Because the calories are the building blocks of body tissues.



** Macronutrients Explained

You body needs each of the 3 macronutrients in relatively large quantities to function properly. 

*** Proteins

Proteins helps with... 
- Producing antibodies for the immune system
- Manufacturing hormones
- Aiding in the digestion and absorption of food
- Maximizing the transport of oxygen to the tissues
- Providing structure for muscles, tendons, ligaments, organs, bones, hair, etc.

**** What happens when you consume proteins 

90% of the proteins you eat is broken down into amino acids
=> becomes part of the amino acid 'pool' that your body draws upon when it needs to build or 
 repair a muscle or any other tissue. 

Amino acids have no form of storage in the body so it's important to have some proteins every day. 

***** Amino Acids

= building blocks of protein

Necessary to support muscle growth

Divided into two subgroups: essential and non essential: 
- Essential (body cannot create them) => must be obtained from food or supplementation
- Non essential (body can create them)


*** Complete and Incomplete Proteins
- Complete protein: offers all essential amino acids
- Incomplete protein: missing one or more essential amino acids

- All animal proteins are complete proteins
- Plant-based proteins are generally incomplete


**** Tip for Vegans

To get all the essential amino acids make sure to get protein from a variety of sources

This compensate the lack of specific amino acids in specific foods

Consume a balanced diet including grains, vegetables and legumes, nuts and seeds.


*** How much protein do you need 

Ideal protein intake will depend on factors such as weight, muscle mass and fitness goals.

**** Optimal Daily Protein Intake

- To live a healthy life: 0.5 - 0.7 grams per pound of bodyweight
- To build muscle: 0.8 - 1 gram per pound of bodyweight
- To lose fat and maintain muscle: 0.8 - 1 gram per pound of bodyweight


*** Carbohydrates

*** Dietary fats
