* Meal Planning Basics

#+BEGIN_QUOTE
Without a strategy and a plan, a goal is no more than a dream.
#+END_QUOTE

#+BEGIN_QUOTE
Create the body of your dreams while still eating your fafourite food.
#+END_QUOTE

#+BEGIN_QUOTE
Your goals might be to lose weight, to gain weight, to lose fat or to gain muscle, or simply live a healthy life. 
Whatever your goals might be, Nutrimium is meant to help you to reach your goals.
#+END_QUOTE


** Meal Planning Explained

The most important principles in dieting and nutrition are (by order of importance decreasing):
1. *Calorie Balance* (= How Much You Eat)
2. *Macronutrient Amounts* (= What You Eat => Protein, Carbs, Fats)
3. Nutrient Timing (= When You Eat)
4. Food Composition
5. Supplements


** Calories explained

*** A calorie

Energy needed to raise temperature of 1 litre of water by 1 degree Celsius. 

A calorie = form of energy measurement.

When you eat food, you consume the energy that stored within the food.

*Energy can be stored for ater use (as glycogen or fat)*

*** Calorie Balance

3 different states of calorie balance. 

You can only be in ONE state at a time:

- Negative calorie balance => will result in weight loss
- Neutral calorie balance => no change in the weight
- Positive calorie balance => weight gain

The calorie balance will determine how much you can gain/lose over any given period of time.
Because the calories are the building blocks of body tissues.



** Macronutrients Explained

You body needs each of the 3 macronutrients in relatively large quantities to function properly. 

*** Proteins

Proteins helps with... 
- Producing antibodies for the immune system
- Manufacturing hormones
- Aiding in the digestion and absorption of food
- Maximizing the transport of oxygen to the tissues
- Providing structure for muscles, tendons, ligaments, organs, bones, hair, etc.

**** What happens when you consume proteins 

90% of the proteins you eat is broken down into amino acids
=> becomes part of the amino acid 'pool' that your body draws upon when it needs to build or 
 repair a muscle or any other tissue. 

Amino acids have no form of storage in the body so it's important to have some proteins every day. 

***** Amino Acids

= building blocks of protein

Necessary to support muscle growth

Divided into two subgroups: essential and non essential: 
- Essential (body cannot create them) => must be obtained from food or supplementation
- Non essential (body can create them)


*** Complete and Incomplete Proteins
- Complete protein: offers all essential amino acids
- Incomplete protein: missing one or more essential amino acids

- All animal proteins are complete proteins
- Plant-based proteins are generally incomplete


**** Tip for Vegans

To get all the essential amino acids make sure to get protein from a variety of sources

This compensate the lack of specific amino acids in specific foods

Consume a balanced diet including grains, vegetables and legumes, nuts and seeds.


*** How much protein do you need 

Ideal protein intake will depend on factors such as weight, muscle mass and fitness goals.

**** Optimal Daily Protein Intake

- To live a healthy life: 0.5 - 0.7 grams per pound of bodyweight
- To build muscle: 0.8 - 1 gram per pound of bodyweight
- To lose fat and maintain muscle: 0.8 - 1 gram per pound of bodyweight


*** Carbohydrates

The bodies preffered energy source. More specifically, carbs are sugar molecules that are a union 
of carbon, hydrogen and oxygen (CHO). Your body breaks carbs down into glucose, which is transported 
throughout the body to provide energy.

Any glucose not used is stored in your liver and muscles as glycogen or as fat.

**** Benefits of Cabs

- During high intensity activities your body uses glycogen and converts it back to glucose for new fuel. 
- Supply the nervous system with fuel => more concentration, more fatigue resistance and more motivation
- Reflueling glycogen stores
- Secreting insulin => helps tissues to grow

**** Types of Carbs
3 types of carbohydrates: 

1. Monosaccharide - one sugar molecule (simple) - eg. glucose and fructose
2. Disaccharide - two sugar molecules (simple) - eg. lactose, maltose, table sugar
3. Polysaccharide - several sugar molecules (complex) - eg. fiber, pasta, rice

Simple carbs are easily absorbed by the bloodstream because of the simple molecular structure.
Complex carbs on the other hand takes more time to the body to break down into sugar.


The *glycemic index* measures the speed with which carbohydrates are converted to glucose.

Foods that digest quickly are higher on the index and foods that digest slowly are lower on the index. 
This is important because large spikes on insulin levels can make you even more hungry, can negatively 
impact fat loss and lead to diabetes.

***** Examples

****** Low GI Foods (55 or less): 
- Oatmeal
- Sweet potato
- corn
- beans
- peas
- legumes and lentils
- most fruits and non-starchy vegetables


****** Medium GI (56-69):
- Whole wheat
- rye and pita bread
- quick oats
- rice
- couscous


****** High GI (70 or more)
- White bread or bagel
- corn flakes
- puffed rice
- bran flakes
- instant oatmeal
- russet potato
- pumpkin
- popcorn
- melons and pineapple


***** Problems with the glycemic index
Foods aren't adjusted on a per servings basis => glycemic load.

Glycemic index only measures impact of isolated foods on blood sugar levels.

Combining carbohydrates with different foods like dietary fat, slows down the pace of digestion and
therefore lowers its impact on blood sugar levels.

*Simple rule: If you are eating whole, unprocessed carbs, consider them a good, but if the carb has been processed it's a "bad" carb.*

***** Do bad carbs make you fat ?

Carbs themselves do not make you fat. 
Howevwer, many processed foods are high in sugar and other types of simple carbs. These foods often lead to cravings and can 
make it easier to overeat even if you already filled up your daily calories but are still hungry. This is why many people who 
follow a diet that is based around these foods will see weight gain over time.

But to get fat you always need a calorie surplus which you could also reach with a high protein or high fat diet.

As long as you include quality carbs in you diet you will be fine. 

**** How many carbs should you eat per day 
In theory there is no true minimum from the perspective of general health.

However, for athletes, chronically dipping too low in carbohydrates intake will lead to poor workout performance,
poor muscle growth and more fatigue due to glycogen depeltion.

Optimal intake depends on a variety of factors but even without knowing your exact measurements we can still narrow
in on a range using only your bodyweight and training intensity.

| Light Workouts    | 1 - 1.25g per lb   |
| Moderate Workouts | 1.25 - 1.5g per lb |
| Hard Workouts     | 1.5 - 1.75g per lb |

- Light workouts: 30 minutes or less or less than 10 working sets
- Moderate workouts: between 30 and 60 minutes or more than 10 working sets
- Hard workouts: anything more intense than moderate workouts


***** Can you eat too much carbs 
For most active people and athletes, there does not seem to be such a thing as an excessive intake of carbohydrates, so long
as minimal protein and fat intakes are met.

We know from studies done with endurance runners and vegetarians that diets very high in carbs can be very healthy in 
the long term. This assumes though that you get your carbs from quality sources.

If you exercice a lot and need the extra energy then you can consume large amounts of carbs as long as you get 
then from complex carbs and you also get your minimal protein and fat needs.

Also keep in mind that some people's stomach simply don't react well to a high carb diet. They will feel bloated and full 
and somewhat tired throughout the day. For all these people I recommend to keep the carb intake at the level in the last table and 
reach any other calories to health fats.


*** Dietary fats

Your body needs fatty acids to survive and cannot produce them from other foods.

Fat is needed to regulate hormone production, keep your skin and hair healthy, and
to absorb vitamins A, D, E and K (fat-soluble vitamins).

Fat cells insulate your body and help to keep you warm.

**** Types of Fat
There are two main types of fat:

- *Saturated fats* (eg. butter, cheese, whole milk) were long believed to raise LDL cholesterol level,
however recent studies suggest it's a lot less problematic. They are solid at room temperature.

- *Unsaturated fats* lower your LDL cholesterol level (include olive and canola oil, safflower, sunflower,
corn and soy oil).

There are also other types like *Trans fats*: form when vegetables oil is 
infused with hydrogen => avoid (eg. oil, butter and margarine) !


**** How much fat should you consume

Ideal Daily Fat Intake:
- 0.3 grams per pound of fat-free mass per day
- roughly 15 to 20% of daily calories 
- limit saturated fat intake, avoid artificial trans fats, and favor monounsaturated and polyunsaturated fats (unsaturated).

**** When to increase fat intake 

When all carbohydrates, fat and protein needs are already met, but your daily calories are not yet filled 
you have a choice to make => more proteinm fat or carbs?

In many cases, adding fat is good option because of:
- Taste
- Health effects
- Calorie density (9 cals vs 4) => ease of consumption
- Cost effectiveness


** Meal Timing  

*** Introduction

Even if meal planning has its importance, its effects are often overestimated.

*** Protein timing 

Even though the body can't store excess protein you don't have to eat 1 meal every 3 hours.

Our goal is to create a continual supply of amino acids.

The one variable we need to look at is protein digestion -> how fast or slow the consumed food is broken down into amino acids.

How long this process takes depends on three factors: 
- Protein type
  - Fastest digesting protein: whey (under 1 hour)
  - Medium: whole food proteins (several hours)
  - Slowest: dairy products (Up to & hours)
- Meal size
  - The simple addition of more food can prolong the digestion time of any protein source
  - Even more protein itself can delay absorption times
- Fat and fiber content
  - Bot fat and fiber will prolong the digestion of proteins to a considerable extent
  - A large, fatty steak can take as long to digest as a casein source
  

**** Meal frequency 

Your goal is to maintain a continual supply of amino acids to the muscle.

There are different ways of achieving this.

You can eat 6 smaller meals but you can also just eat 3 meals as long as they are large enough to cover both you daily protein needs
and are slowly digested.

**** Protein Timing and workout 

As long as you meet your daily calorie and nutritional requirements through your normal diet you don't have to drink a protein shake 
right before or after your workout. 

Instead get a =pre= and =post= meal right, which is something we will cover in a later lesson.

*** Carbohydrates timing 

**** Meal frequency 

With carbs meal frequency is not generally an issue unless you want or need to consume a lot.

You can again eat them in two or six meals throughout the day.

What's more important is that you time your carbs according to your workout schedule.

**** Carb timing and workout 

Eat some form of carbs before and after your workout.

Eating carbs before your workout will provide your muscles with additional fuel for your training, which will 
indirectly affect your muscle growth because it will help you train more intensively.

Eating carbs after your workout will refill glycogen stores which have been depleted.

Also including cabs in your post workout will quickly insulin levels and keep them elevated for a longer period of time. 
As mentioned earlier, insulin has anticatabolic properties which means it slows the rate of protein breakdown that occurs after 
the exercice.

**** Fat timing 

Fat timing is very simple. 

The only time you should avoid fats is right before your workout, since fat slows down the digestion of both carbs and proteins. 

Additionally, fat can be used to time meals over long intervals. This will maintain glucose and amino acids levels for a larger period of time.


** Pre workout meal

It's main function is to fuel the workout itself and maximize your performance.

In a scientific sense it's meant to do three things:
- Reduce muscle glycogen depletion 
- Reduce muscle protein breakdown
- Reduce post workout cortisol levels


*** Guidelines

Eat a balanced meal with 0.2 - 0.25g/lbs of your target bodyweight (for both carbs and proteins) up to one hour before your 
workout.

If your last meal lies more than two hours prior to your training, consume liquid or easily digested protein and carbs
30 minutes before your workout.

*** Suggestions

- Meals that you can eat up to 1 hour before your workout: 
  - Oatmeal with Whey Protein
  - Large chicken sandwich with wholegrain bread
  - 2x or more Hard-Boiled Eggs on an Avocado Toast 
  - Whole Grain pasta with some sort of protein

- Snacks 30 min or less before your workout:
  - Banana with whey protein shake
  - Apple wedges with cinnamon (and some light protein source)
  - Protein bar



** Post-Workout Meal

Meant to supply your body with everything it will need to repair the muscle tissue.
Specifically, the goal is to accomplish the following:

- Replenish muscle glycogen that was depelted during your workout
- Reduce muscle protein breakdown caused by exercice
- Increase muscle protein synthesis
- Reduce muscle soreness and fatigue
- Enhance overall recovery
- Reduce cortisol levels


Give your body the same macronutrients you did in the pre workout meal: Carbs and Protein (around 0.2 - 0.25g/lbs of your target bodyweight).

If you're really hungry you can increase the carbs.

Timing should be around 30-60 minutes after your workout.

Pre and post workout meals shouldn't be separated by more than 3-4 hours.

** What about the anabolic window
Studies have shown that under 60 min is still ok.


** Food composition

*** Introduction

Food composition will have a very minor impact on the goals. 

*** Protein Composition

*Bioavailability*: what percentage of the protein that you consume is actually absorbed into the bloodstream.

Another indicator of protein quality considers how much of the protein is composed of essential amino acids.
Obviously food that are high in essential amino acids are of high quality in this sense.

List of foods ranked by protein quality starting with the most quality sources:

- Whey Protein Isolate
- Whey Protein Concentrate
- Egg Sources (Cooked not raw)
- Meats (beef, pork)
- Poultry (chicken, turkey)
- Fish and seafood
- Soy protein and quinoa
- Combined plant sources (like beans and rice)
- Isolated plant sources (whole grain bread by itself, nuts by themselves)

BUT there is nothing worst for your physical and mental health than a one sided diet even though nuts for example aren't the highest quality proteins
they are a great source of fats and micronutrients. The same goes for other plant based sources of protein and fish and seafood.

*** Carbohydrate Composition

Just like protein composition, carbohydrate composition can refer to several concepts.

The most commom is the glycemic index which we already talked about in the lesson on the different types of carbs.

GI rankings are based on the glycemic effects of specific foods that are consumed isolated and fasted state.

Unless you have a pre-existing health condition, the human body is very good at keeping your blood sugar levels and insulin levels within a 
fairly precise range.

In real world scenarios, it really is not as important as mnany people make it out to be having your blood sugar or insulin levels increased
to higher than normal rate isn't going to have any major impact on muscle building or fat burning goals. Instead of comparing fast carbs and 
slow carbs, here is what you should focus on: 

Get the majority of your carb intake form high fiber, minimally processed source. This includes foods such as oatmeal, rice (brown or white),
potatoes, whole grain pasta, fruits and vegetables.

Consume your carbs as part of a complete meal with protein and healthy fats.

*** Fat Composition

For muscle building and fat burning, fat composition is even less important than protein and carbs composition.

Consuming certain kinds of fats and staying away from others will make a difference in your overall health.


| Fat type               | Recommended intake | Example foods                                                 |
|------------------------+--------------------+---------------------------------------------------------------|
| Monounsaturated        |                60% | Avocado, nuts and their butters, olive oil                    |
| Polyunsaturated        |                15% | Vegetable oils                                                |
| Healthy saturated      |                15% | Coconut/macadamia nut oils, grass fed animal fats             |
| Conventional saturated |                10% | Fats from conventionally farmed bacon, eggs, cheeses, butters |
| Trans                  |                 0% | Store-bought baked goods, most fast food                      |




** Supplements

Supplement can never replace proper diet planning and nutrition, but they can help you reach your fitness goals faster.

*** Protein powder

Even though you don't have to use protein powders to reach your recommended 
daily protein intake, consuming enough protein every day can be tricky. 

It most lokely won't matter all that much which kind of protein you buy as long as you take it regularly.

Optimal dosage: max. 30% - 50% of your daily protein intake.

*** Creatine

An organic acid that helps supply the muscle cells with energy for muscle cells during high-intensity, short duration exercice.

It also doesn't build muscle by itself, but it will increase your strength level.

Optimal dosage: 3-5 grams per day.

*** Fish Oil 

Boosts your mood, helps maintain healthy cholesterol levels and strong bones and ligaments.

Basically no side effects unless you are allergic to it.

Optimal dosage: 1000-3000mg of combied EPA/DHA per day.

*** How to use protein powder


**** Is a protein powder absolutely necessary to build muscle?

No.

As long as you reach your recommended daily protein intake you will be fine and see results.

However, consuming enough protein every day can be tricky, especially when you don't have time to prepare high protein meals all the time.

**** What time of protein powder is best?

There are a lot of protein powders you can buy (eg. whey, casein or egg).

As long as you don't get all your daily protein from supplements you won't notice the tiny differences among the different forms of protein.

Differeces in protein powder don't matter if rest of your diet is balanced enough to supply you with all essential amino acids.

**** When should you take protein powder?

Protein timing isn't really as important as people make it out to be.

Some studies show a positive effect on post workout protein on protein synthesis, while others find no such relation.

As long as you meet your daily calorie and nutritional requirements through your normal diet it doesn't matter when you take your 
protein shake.

**** How much protein powder shoul you take?

The majority of your diet should always be based on whole foods.

Depending on your lifestyle suggest you get around a third to half (maximum!) of your protein from protein shake.


**** What is the best liquid to mix protein powder with?

Water is ideal for any calorie restricted weight loss diet.

Milk will provide you some additional protein but also leads to a higher calorie count.

Other alternatives include soy or almond milk.

*** How to use creatine

**** Benefits of creatine

Creatine helps supply the muscle cells with energy during high-intensity, short-duration exercise.

Even though it is a non-essential nutrient, because our body can produce creatine naturally, supplementation makes sense as it will further improve
performance.

Creatine help produce ATP more quickly, which is the primary energy molecule used during weight training.

**** Which type of creatine should you use?

Creatine monohydrate is the most effective form of creatine.

While variations like Kre Alkelyn (buffered creatine) or creatine ethyl ester are often sold for more than double the normal price, scientific 
studies showed no additional benefits.

To make sure you are getting 100% monohydrate, look for the Creapure trademark.

**** When should you take creatine?

Creatine doesn't have immediate effects, so its timing really doesn't matter.

Taking it before your exercice won't lead to increase strength.

**** How much creatine should you take?

3-5g per day (about a teaspoon).

This is enough to saturate the muscle within 2-4 weeks and enough for maintenance afterward.

Taking in more won't lead to better results as you will pee out the excess creatine.

**** With what liquid should you mix creatine?

Whatever drink you prefer.

High sugar drinks don't lead to an increase in creatine uptake.


**** Do you need a "loading phase"?

No.

A "loading phase" involves taking 20g per day for 5-7 days before switching to the recommended dose of 3-5g per day.

The higher initial dose will lead to a faster saturation of the muscle cells, but only by a few days and the normal dose will 
also get you there.

**** Do you have to cycle creatine?

No.

There are no studies that linked continued creatine use with health risks or a decrease in the body's natural production of creatine.

If you want to stop taking creatine, your body won't undergo any withdrawal symptoms (beside the decrease in strength).


*** Other supplements to consider

**** Pre-workout supplements

Most of them are extremely overpriced.

In 99% of the cases the boost comes from the caffeine.

You will save a lot of money if you simply buy caffeine and maybe L-Tyrosine separately and take both 30-45 minutes 
before your workout (100-200mg caffeine and 1000-3000mg of L-Tyrosine).

**** Fat burner supplements

Fat burner themselves don't burn fat.

Most fat burners will slightly increase your metabolism through a few key ingredients: caffeine, synephrine, green tea extract, 
naringenin and hesperidin.

For beginners it's a lot more important to understand how to come up with the right diet and stick to it than how to choose the right fat burner.


* Setting up your diet

** How to determine your optimal calorie intake

Nothing really useful here.

** Tracking calories

You will need three things: 
- food
- calorie tracker app
- kitchen scale 

In this lesson we'll learn how to utilize our scale to accomplish two things: 
1. Ensuring that your calorie and macro counting is sufficiently accurate
2. Making the overall process easier and less time consuming 


** Determining Protein Intake
Optimal protein intake is about 0.8g to 1.0g per pound of body weight 

If you want to be even more specific there are two factors that determine where exactly you are on this range: 
1. body fat - the more you are lean, the more muscle you have, the more protein your body needs
2. activity level - the same goes for activity level

So if you train, go closer to the upper bound of 1.0g per pound of body weight.

** Determining Carbohydrates Intake

*** Ideal Carb Intake

Depends mostly on the activity level.

| Workout intensity | Ideal Carb Intake  |
|-------------------+--------------------|
| Light Workouts    | 1 - 1.25g per lb   |
| Moderate Workouts | 1.25 - 1.5g per lb |
| Hard Workouts     | 1.5 - 1.75 per lb  |

- Light workouts: 30min or less or less than 10 working sets.
- Moderate workouts: between 30 and 60 minutes or more than 10 working sets.
- Hard workouts: anything more intense than moderate workouts.


*** What about rest days?

You can keep the same meals even if you don't train. 

** Determining Fat Intake

At least 15% - 20% of your total calories.

** What about the remaining calories

It's up to you but:

- it is not recommended to go over 1.0g of protein per pound of body weight because you won't notice extra muscle growth
  plus quality meat is expensive.
- instead go for additional carbs or fat
- if you are very active, carbohydrate is a good option, it will provide you with more energy
- if however you're overweight or not very active then fats will be a better option here (make sure to take quality sources)


** Determining meal structure

- Number of meals (3-8)
- Protein intake around activity
- Carb intake around activity
- Fat intake around activity



** Quality protein source

Once you've determined the meal structure you'll probably wonder what protein are quality protein sources.

*** Dairy and eggs
- Greek yogurt
- Cottage cheese
- Swiss cheese
- Eggs
- Milk
- Whey protein



*** High-Protein meat
- Lean cut steak
- Ground beef
- Pork chops
- Chicken breast
- turkey breast


*** High-Protein seafood
- Tuna
- Halibut
- Salmon
- Tilapia


*** High-Protein canned foods
- Anchovies
- Corned beef
- Sardines
- Beans


*** High-Protein snacks
- Jerky
- Peanut Butter
- Nuts


*** Vegetarian and vegan sources
- Beans
- Chickpeas
- Nuts and nutbutters
- Tofu
- Chia seeds
- Leafy greens



** Quality carb sources

*** High carb whole grains
- Whole grain bread
- whole grain pasta
- whole grain cereal (no sugar)


*** High carb fruits
- Bananas
- Mangos
- Apples
- Oranges
- Pears


*** High carb legumes
- Beans
- Peas
- Lentils



*** Other sources 
- (sweet) potatoes
- (brown) rice
- quinoa
- oatmeal
- tortillas


** Quality fat sources

*** Sources of unsaturated fats
- Avocados
- Salmon
- Olive and olive oil
- Nuts and nut butters (when not highly processed)
- flaxseed
- tuna
- dark chocolate
- sunflower seeds


*** Sources of saturated healthy fats
- Whole eggs
- High quality meat
- Full fat milk
- chicken breast


*** Sources of trans fat to limit or avoid
- Pizza
- Hot dogs
- Hamburgers
- any type of fast food
- any type of fried food






* Adjusting Your Diet For Weight Loss And Muscle Gains

** Adjusting you diet to build muscle

*** Why do you need a bulking diet?

In order to force your body to grow new muscle tissues we need to lift heavy and consume extra calories

*** The ultimate bulking diet

1. Calculate your Total Daily Energy Expenditure (TDEE).
2. Add a certain percentage to your TDEE.
3. Reach this calorie count by eating (mostly) healthy foods.


*** Adding to your TDEE

Some recommend 10-15% additional calories. This part is probably the most controversial part of any bulking program.

Other recommend 20% additional calories.

How large your daily bulking calorie count has to bem comes down to how your metabolism reacts to more food.


** Adjusting your diet for weight loss

*There is a difference between "weight loss" and "fat loss"*

The former is a lot easier than the latter. 

The science behind weight loss is simple: *weight loss = calories in vs. calories out*

The rules to lose body fat are a bit more complicated: *Fat loss = negative calorie balance + right balance of macronutrients*

*** Creating a calorie deficit

1. Calculate your Total Daily Energy Expenditure (TDEE)
2. Subtract a certain percentage from your TDEE
3. Reach this calorie count by eating (mostly) healthy foods.


Again the percentage to subtract is highly controversial. In general there is 3 different categories of calorie deficit
- Small: 10-15% below TDEE
- Moderate: 20-25% below TDEE
- Large: more than 25% below TDEE

*Very few sources recommend a Large deficit.*

The argument for a small deficit is that it would lead to less loss of muscle. However studies have shown that large deficit don't necessarily 
means more muscle loss if you maintain a strict workout regimen. Plus if your goal is to lose body fat fast a deficit of 20% below your TDEE 
would probably be the best option. However for some who have a fast metabolism a smaller deficit would most likely show similar results while at the
same time sacrificing less strength and at the same time giving you more to eat during your diet.

*** Maintaining high protein intake  

0.8g and 1.0g of protein per pound of body per day.

If your diet involves a very large calorie deficit and you are already very lean, you might even want to go with 1.2 grams of protein (although 
usually 1g should be enough).

*** Calorie Cycling (OPTIONAL)

You can try eating more calories on workout days and fewer on rest days while staying on a long term calorie deficit for instance when measured over 
the week. The logic behind this strategy is to maximize strength and recovery on the days you exercise while providing less calories when less 
energy is expanded on rest days.

It's not a proven method but the psychological benefit of eating more on workout days can make dieting more tolerable.

** Cheat Days and Cheat Meals

*** Do cheat meals have any negative effect on your overall diet progress?

No, as long as you keep your calories and macros in check. Calorie balance and macronutrients are the most important aspects of the diet. 

Proper nutrition is all about the big picture. If you're eating clean the rest of the time and then take a piece of pizza it's not harmful.

*** Cheat meals 

80-90% of your diet should come from "clean" and healthy foods.

10-20% can come from whatever foods you like as long as it fits your total daily calories and proteins, carbs and fats.

Stick to the basics of correct dieting and "cheat meals" are not going to magically cause you to get fat or lose muscle.

*** Cheat days 

Unlike cheat meals, cheat days can have a drastic impact on your overall diet success.






** Post-Workout Shake 

*** Do you even nedd a post-workout shake? 

The short answer is no. No research support the claim the you need carbs just after yoiur workout to avoid muscle breakdown. 
The case for post-workout protein is a bit more complicated, some studies shown a positive effect on protein synthesis while other find 
no relation. 

*** Does that mean a post workout shake completely useless? 

Not so fast, as you'll see there is still an argument to a post workout shake to be made.
It still makes sense to eat proteins and carbs 1-2 hours after your workout as mentioned previously. And some days you don't 
have time to prepare a meal right after your workout so in this case, a post-workout shake makes sense. They are quick to prepare and easy 
to eat while you're on the go. 

Exemple: 
- Carbohydrates: 40-50g of instant oats
- Protein: 30g+ of whey protein
- Optional: 1 banana and/or peanut butter


* Healthy Dieting

** Healthy dieting introduction

Healthy dieting in about understanding and designing you diet not just in a context of fitness but also overall health and well being.

** Dieting Myth #1: Carbs are bad for you 

Insulin itself in not bad. Actually it used to store glucose which is the sugar in you blood, and use it to use it for energy. 

There is some evidences that carbs can cause insulin sensitivity, but only in people with prediabetes that overheat high sugar carbs.

So yes, if you don't exercice and your diet consists mostly of these type of carbs then they will negatively affect your health.

However, if you follow a well balanced diet and exercice regularly then quality carbs will actually be necessary to fuel your workout.

** Dieting Myth #1: Fats are bad for you 

Cutting all fat from your diet can be dangerous, since your body needs it for hormone production.

Many low fat products contain more calories than their normal counterparts.

There is no evidence that saturated fats are the direct cause of heart problem.

Trans fat is the only kind of fat that is directly linkled to health problems.

** Dieting Myth #3: Protein is bad for you

Healthy adults who exercice have no problems with consuming high amounts of proteins both in regards 
to kidney problems or other health problems.

If you have an existing renal disease or existing kidney problems than limit your protein intake. 

Elderly individuals at risk of bone density issues and osteoroposis should aim to consume more protein.

*** The Truth About Protein Shakes

Whole foods should always be components of a balanced and nutritionally optimal diet.

But food is not always the most efficient, easiest or even preferred to get a dose of high quality proteins.

When following a strict diet, getting the correct amount of protein often requires people to get protein from 
supplements.

** Dieting Myth #4: Eating Eggs Raises Cholesterol 

In clinical trials, no association was found between eggs and cardiovascular disease (in healthy adults).

In unhealthy and/or overweight people with egg consumption might negatively affect blood levels of cholesterol and lipoproteins.

Bottom line: Eggs are a great source of proteins, fats, and other nutrients. 

** Dieting Myth #5: Avoid Salt At All Cost

Salt (sodium) is an essential mineral; its consumption is critical to our health.

The problem is that the average person consumes double the recommended intake.

In most people, there appears to be little to no association between salt consumption and hypertension.

Bottom line: Salt isn't strongly associated with high blood pressure, except in people with salt-sensitive hypertension. 
Still, anything in excess is harmful, and sodium is no exception.

** Dieting Myth #6: Eat Several Small Meals To Lose Weight

Food intake has only a minor effect on metabolism. 

Eating frequently may have benefits for some people, but it is incorrect that this affects the amount of 
calories we burn.

What most affects your basal metabolic rate (BMR), the rate at which your body burns calories at rest, is body composition 
and size. More muscle and big bodies generally burns more calories overall.

Watch your calories and build up your muscles instead.

** Dieting Myth #7: Diet Foods Lead To Weight Loss

Low-fat and low-carbs don't always mean low-calories.

Studies have shown that participants ate up to 50 percent more of food that researchers falsely labeled "low-fat"
than they did of the same exact foods with real labels.

When you're tampted by a snack food that's labeled "light"or "low-fat" check the nutrition label. 


** Dieting Myth #8: Eating Red Meat Causes Cancer

Almost everything we eat has the potential to be involved in cancer development.

Current evidence suggests that red meat can pose a cancer risk for people with poor diets and 
lifestyle choices.

Various compounds produced in meats during cooking and processing have possible cancerous effects but their aggressiveness
depends on the preparation method.

*** What can you do to reduce the risk ?

Stop smoking, set up a balanced diet with more vegetables and start exercising.

Marinating meat before cooking it reduces harmful so does baking and broiling. 

Bottom line: Fears about cancer and red meat are probably true but exaggerated.

* Common Dieting Trends Explained 

In this section we're going to talk about current diet trends. As you'll see the diet industry is like the fashion industry 
with trends everyone seems to follow. Sometimes these diet trends makes sense but oftentimes they are just passed that won't
stand the test of time. The problem with theses diets is that it's easy to loose track especially if you are not a profesional fitness
coach.

** Gluten Free Diet Explained

Gluten is a naturally occuring composite of two proteins (gliadin and glutenin) that is mostly found in rye, wheat, 
and barley products.

Gluten molecules aren't broken down by heat or directly digested -> can be problematic for people with 
celiac disease (.3-1.2% of the pop.)
They can be absorbed by the small intestine and cause an autoimmune response. 

According to recent studies, there is between 6 and 7% of people with gluten sensitivity who suffer from similar symptoms.

However, the vast majority of people don't need to follow a gluten free diet. 

*** The Problem with Gluten Free Diets

A gluten-free diet itself offers no special health benefits.

Most gluten-free foods tend to be less nutritious, lower in protein, higher in fat and cost more than double.

Gluten free does not help with weight loss.

If you want to play it safe, limit your gluten intake to a few meals a week. 


** Paleo Diet Explained

The idea behind the paleo diet is to eat the same food our hunter-gather ancestors supposedly ate (fruits, vegetables, meats, 
seafood, and nuts).

Avoid processed foods, dairy products, potatoes and grains. 

Many of the aspects of paleo dieting are very healthy. 

*** The Problem with Paleo Diets

Many nutritious foods are forbidden, such as:

- Whole Grains
- Dairy Products
- Some legumes

*Bottom line:* There is nothing wrong with the foods paleo recommends. The problem comes with the foods that should be avoided. 
If you want to follow the paleo diet, go with a less drastic approach and still include some form of non-Paleo when needed.

** Low-Carb Diets Explained

Low in carbohydrates

Compensate with more protein and/or fat

Carbs are a non essential macronutrient -> in theory there is nothing wrong with low carb.

*** The Problem With Low-Carb Diets

Much of the critique against carbs holds true only for simple carbs.

In fact if you regularly exercice then not consuming complex carbs will hurt your strength level and therefore your muscle gains.
You'll feel weaker and your workout will become very difficult if you don't provide your body with the fuel in the form of complex 
carbs.

If you want to build muscle, low carb diets are not recommended. 

*** Does Low-Carb Help With Weight Loss ?

If you are completely sedentary it makes sense to cut carbs you don't need the energy.

Also people who consume primarily simple carbs will benefit from eating less of them.

A low-carb diet basically guarantees that you're going to struggle with hunger.

Different people react differently to more/less carb intake so it can make sense to try it out at least once.


** Intermittent Fasting Explained

The average person probably eats food from around 8 AM to maybe 9 PM.

-> You eat for 13 hours and eat nothing for about 11 hours.

Intermittent fasting has you fast for 16 hours and eat for 8.

*** Research on Intermittent Fasting 

Meta study concluded that IF is not superior to traditional dieting.

Found no significant benefits related to body composition, fat loss, insulin sensitivity, or hormones.

IF makes sense for 

1. Anyone who doesn't have the time or discipline to eat 5 or 6 meals per day
2. Anyone who has trouble counting calories



** Vegan Diet Explained

Vegans do not consume animal products and byproducts.

You can build muscle on a vegan diet, but it's more difficult.

The main difference between vegan and traditional diets is protein intake.

Veganism replaces high protein animal products with low protein plant based products. 

Combine your protein sources to get all the essential amino acids. 

Get the majority of your daily protein from wheat, rice, oats, peas, beans, potato, almond, peanuts, walnuts, quinoa and buckwheat.
Also make sure to combine one with another to get all the essential amino acids.

*** Veganism and Vitamin Deficiencies

Vitamin deficiencies are possible.

Unless micromanage your diet you will have to supplement.

*Bottom line:* You can build muscle and strength as a vegan... if you know what you are doing. Closely monitor your foods and protein 
sources and invest more time towards meal planning to avoid deficiencies.

* Micronutrients

** Vitamin A

Fat-soluble vitamin needed to maintain eyesight and prevent night blindness.

Improves immune system, helps with fat storage and protects against infections. 

Also needed to grow new cells, lower cholesterol and reduce the risk of heart disease.

*** Where to get Vitamin A

Animal livers and green and yellow vegetables (sweet potatoes, carots, brocolis, leafy greens such as spinach...).

Fitness experts recommend getting vitamin A promarily from plant sources. 

Recommended Daily Intake: 900 mcg/day in men and 700 mcg/day in women.


** Vitamin B

Several B vitamins that work together in the body. This group includes the following: 

- thiamine (B1)
- riboflavin (B2)
- niacin (B3)
- pantothenic acid (B5)
- pyroxidine (B6)
- cyanocobalamin (B12)
- folic acid
- biotin

Breakdown of carbohydrates into glucose

Breakdown of fats and proteins

Muscle tone in the stomach and intestinal tract

Skin 

Hair

Eyes 

Mouth

*** Where to get Vitamin B

Dark green vegetables, grains, and meat

Deficiencies can occur even in the general population 

Especially vegans and pregnant women are at high risks of B12 deficiencies.

** Vitamin C

Acts as an antioxydant needed for many metabolic functions, including new tissue growth and repair.

Helps produce anti-stress hormones.

Aids to heal wounds and burns and protects against abnormal blood clotting.


*** Where to get Vitamin C 

High levels of vitamin C are found in berries, citrus fruits and green vegetables like broccoli, brussels sprouts and green peppers.

Recommended Daily Intake: 

Men 90 mg/day; Women 75 mg/day


Supplementation make sense when you're sick or starting to get sick.

** Vitamin D

Fat soluble vitamin needed for: 

- growth, development and maintenance of bones and teeth.
- regulating hearthbeat
- protects against muscle weakness

Body can produce it when skin is exposed to the sun's ultraviolet rays.

*** Where to get Vitamin D

High levels of vitamin D are found in eggs, dairy products, and fish oils.
However the prefered source should always be sun exposure.

Recommended Daily Intake: 

600 IU for men and women.

Vitamin D deficiency is relatively common in adults.

-> blood test and check your vitamin D levels.


** Vitamin E

Fat soluble vitamin with several health benefits:

- Effective preservation of food
- Prevention of diseases such as cancer and diabetes
- Promotion of a healthy nervous system
- Protection against heart disease
- Protection for the eyes
 

*** Where to get vitamin E

High levels of vitamin E are found in almonds, raw seeds, swiss chard, spinach and kale.

Recommended Daily Intake:

Men 4mg/day; women 3 mg/day

Supplementation without consulting a doctor first in not recommended.

** Vitamin K

needed for: 
- blood clotting.
- growing and repairing bones.
- conversion of glucose into glycogen.


*** Where to get vitamin K

High levels are found in kale, collard greens and spinach, broccoli, Brussels sprouts, cauliflower

Recommended Daily Intake: 

120 mcg/day for men and 90 mcg/day for women

-> Vitamin K deficiencies occur rarely.

** Calcium

- support muscle function
- transmits nerve impulses
- helps cells to communicate
- involved in the release of certain hormones

Stored in our bones and teeth


*** Where to get Calcium
 High levels are found in yogurt, whey protein supplements, milk, cottage cheese and dark leafy greens.

 Recommended Daily Intake:

 1000 mg/day - 1300mg/day for men and women.

 -> Vegetarians and people with lactose intolerance are the greatest risk for calcium deficiency.

** Magnesium
Necessary for: 

- protein synthesis
- muscle and nerve function
- blood glucose control
- blood pressure regulation
- energy production

Like calcium much of our magnesium is stored in the bones.


*** Where to get Magnesium

High levels are found in dairy products, meat, fish and seafood, green vegetables, leafy greens and nuts.

Recommended Daily Intake:

420 mg/day for men and 310mg/day for women

-> Deficiency are common but please talk to your doctor.


** Phosphorus

Found in the bones, cell membranes and energy molecules.

Used for tissue growth.

Regularly lost through sweat and urine.

*** Where to get Phosphorus

High levels are found in meat, pultry and fish, wheat, potatoes and peanuts.

Recommended Daily Intake:

700 mg/day for both men and women.

-> Getting too much is a more common problem than getting too little.


** Potassium

Necessary for:
- muscle contraction
- nerve impulses
- protein synthesis
- transferring nutrients through cell membranes
- breaking down carbs
- maintain a regular hearth rhythm


*** Where to get Potassium

High levels are found in spinach, potatoes, sweet potatoes, yogurt, meat, poultry, fish, nuts, tomatoes, cucumbers, zucchini,
eggplant and carrots.

Recommended Daily Intake:

4700 mg/day for both men and women

-> You lose a lot through excessive sweating. Here supplementation can be a solution.


** Sodium

Necessary for:

- nerve signaling
- muscle contraction
- fluid balance
- transferring of nutrients through cell membranes (along with potassium)

*** Where to get Sodium

High levels are found in table salt, meat, fish, cheese, pickles, roasted and salted nuts.

Recommended Daily Intake:

1500mg/day for both men and women.

-> Watch out for overdosing and not underdosing.


** Copper

Necessary for:
- production and function of red blood cells
- maintaining blood vessels
- maintaining nerves
- maintaining immune system

*** Where to get Copper
High levels are found in oysters and sellfish, potatoes, beans, nuts, liver, kidneys, dark leafy greens and pepper.

Recommended Daily Intake:

900mcg/day for both men and women.

-> In amounts greater than the upper tolerable limit, copper can be highly toxic!


** Iron 
Important mineral involved in various bodily functions, including the transport of oxygen in the blood.

Essential for providing energy for daily life.

Lost from the body through shedding intestinal cells, sweat and blood loss.

*** Where to get Iron

High levels are found in chicken nuts, vegetables, grains and forified cereals.

Recommended Daily Intake:

8mg/day for men and 18mg/day for women

-> Iron deficiency is uncommon in developed part of the world.

** Zinc
Necessary for: 

- immune system
- cell division
- cell growth
- wound healing
- breakdown of carbohydrates
- senses of smell and taste

*** Where to get Zinc

High levels are found in beef, poultry, oysters, pead, nuts, beans, oatmeal and dairy products.

Recommended Daily Intake:

11mg/day for men and 8mg/day for women.

-> Supplementation can make sens if you have a weak immune system and often suffer from colds.


** Water

*** The Truth About Water

Water is a vital part of your body's detoxification systems. 

Water is used to digest food and shuttle nutrients in your cells.

Water is needed to keep your ears, nose and throat moist.

Water keeps our joint cartillage lubricated and supple, which is vital for preserving joint health.

Brain cells require a delicate balance of water and other chemicals to function properly.

*** How Much Water?

About 20% of our water intake comes from food.

Let thirst be your primary guide.

Guideline: 2.7 liters of water for women and 3.7 liters for men per day.

Add 1 liter per hour of exercice.

*** What Kind of Water?

Even tap water can be contaminated with pollutants.

(Plastic) bottled wtare also contains chemicals.

-> Filtered tap water 

