* Meal Planning Basics

#+BEGIN_QUOTE
Without a strategy and a plan, a goal is no more than a dream.
#+END_QUOTE

#+BEGIN_QUOTE
Create the body of your dreams while still eating your fafourite food.
#+END_QUOTE

#+BEGIN_QUOTE
Your goals might be to lose weight, to gain weight, to lose fat or to gain muscle, or simply live a healthy life. 
Whatever your goals might be, Nutrimium is meant to help you to reach your goals.
#+END_QUOTE


** Meal Planning Explained

The most important principles in dieting and nutrition are (by order of importance decreasing):
1. *Calorie Balance* (= How Much You Eat)
2. *Macronutrient Amounts* (= What You Eat => Protein, Carbs, Fats)
3. Nutrient Timing (= When You Eat)
4. Food Composition
5. Supplements


** Calories explained

*** A calorie

Energy needed to raise temperature of 1 litre of water by 1 degree Celsius. 

A calorie = form of energy measurement.

When you eat food, you consume the energy that stored within the food.

*Energy can be stored for ater use (as glycogen or fat)*

*** Calorie Balance

3 different states of calorie balance. 

You can only be in ONE state at a time:

- Negative calorie balance => will result in weight loss
- Neutral calorie balance => no change in the weight
- Positive calorie balance => weight gain

The calorie balance will determine how much you can gain/lose over any given period of time.
Because the calories are the building blocks of body tissues.



** Macronutrients Explained

You body needs each of the 3 macronutrients in relatively large quantities to function properly. 

*** Proteins

Proteins helps with... 
- Producing antibodies for the immune system
- Manufacturing hormones
- Aiding in the digestion and absorption of food
- Maximizing the transport of oxygen to the tissues
- Providing structure for muscles, tendons, ligaments, organs, bones, hair, etc.

**** What happens when you consume proteins 

90% of the proteins you eat is broken down into amino acids
=> becomes part of the amino acid 'pool' that your body draws upon when it needs to build or 
 repair a muscle or any other tissue. 

Amino acids have no form of storage in the body so it's important to have some proteins every day. 

***** Amino Acids

= building blocks of protein

Necessary to support muscle growth

Divided into two subgroups: essential and non essential: 
- Essential (body cannot create them) => must be obtained from food or supplementation
- Non essential (body can create them)


*** Complete and Incomplete Proteins
- Complete protein: offers all essential amino acids
- Incomplete protein: missing one or more essential amino acids

- All animal proteins are complete proteins
- Plant-based proteins are generally incomplete


**** Tip for Vegans

To get all the essential amino acids make sure to get protein from a variety of sources

This compensate the lack of specific amino acids in specific foods

Consume a balanced diet including grains, vegetables and legumes, nuts and seeds.


*** How much protein do you need 

Ideal protein intake will depend on factors such as weight, muscle mass and fitness goals.

**** Optimal Daily Protein Intake

- To live a healthy life: 0.5 - 0.7 grams per pound of bodyweight
- To build muscle: 0.8 - 1 gram per pound of bodyweight
- To lose fat and maintain muscle: 0.8 - 1 gram per pound of bodyweight


*** Carbohydrates

The bodies preffered energy source. More specifically, carbs are sugar molecules that are a union 
of carbon, hydrogen and oxygen (CHO). Your body breaks carbs down into glucose, which is transported 
throughout the body to provide energy.

Any glucose not used is stored in your liver and muscles as glycogen or as fat.

**** Benefits of Cabs

- During high intensity activities your body uses glycogen and converts it back to glucose for new fuel. 
- Supply the nervous system with fuel => more concentration, more fatigue resistance and more motivation
- Reflueling glycogen stores
- Secreting insulin => helps tissues to grow

**** Types of Carbs
3 types of carbohydrates: 

1. Monosaccharide - one sugar molecule (simple) - eg. glucose and fructose
2. Disaccharide - two sugar molecules (simple) - eg. lactose, maltose, table sugar
3. Polysaccharide - several sugar molecules (complex) - eg. fiber, pasta, rice

Simple carbs are easily absorbed by the bloodstream because of the simple molecular structure.
Complex carbs on the other hand takes more time to the body to break down into sugar.


The *glycemic index* measures the speed with which carbohydrates are converted to glucose.

Foods that digest quickly are higher on the index and foods that digest slowly are lower on the index. 
This is important because large spikes on insulin levels can make you even more hungry, can negatively 
impact fat loss and lead to diabetes.

***** Examples

****** Low GI Foods (55 or less): 
- Oatmeal
- Sweet potato
- corn
- beans
- peas
- legumes and lentils
- most fruits and non-starchy vegetables


****** Medium GI (56-69):
- Whole wheat
- rye and pita bread
- quick oats
- rice
- couscous


****** High GI (70 or more)
- White bread or bagel
- corn flakes
- puffed rice
- bran flakes
- instant oatmeal
- russet potato
- pumpkin
- popcorn
- melons and pineapple


***** Problems with the glycemic index
Foods aren't adjusted on a per servings basis => glycemic load.

Glycemic index only measures impact of isolated foods on blood sugar levels.

Combining carbohydrates with different foods like dietary fat, slows down the pace of digestion and
therefore lowers its impact on blood sugar levels.

*Simple rule: If you are eating whole, unprocessed carbs, consider them a good, but if the carb has been processed it's a "bad" carb.*

***** Do bad carbs make you fat ?

Carbs themselves do not make you fat. 
Howevwer, many processed foods are high in sugar and other types of simple carbs. These foods often lead to cravings and can 
make it easier to overeat even if you already filled up your daily calories but are still hungry. This is why many people who 
follow a diet that is based around these foods will see weight gain over time.

But to get fat you always need a calorie surplus which you could also reach with a high protein or high fat diet.

As long as you include quality carbs in you diet you will be fine. 

**** How many carbs should you eat per day 
In theory there is no true minimum from the perspective of general health.

However, for athletes, chronically dipping too low in carbohydrates intake will lead to poor workout performance,
poor muscle growth and more fatigue due to glycogen depeltion.

Optimal intake depends on a variety of factors but even without knowing your exact measurements we can still narrow
in on a range using only your bodyweight and training intensity.

| Light Workouts    | 1 - 1.25g per lb   |
| Moderate Workouts | 1.25 - 1.5g per lb |
| Hard Workouts     | 1.5 - 1.75g per lb |

- Light workouts: 30 minutes or less or less than 10 working sets
- Moderate workouts: between 30 and 60 minutes or more than 10 working sets
- Hard workouts: anything more intense than moderate workouts


***** Can you eat too much carbs 
For most active people and athletes, there does not seem to be such a thing as an excessive intake of carbohydrates, so long
as minimal protein and fat intakes are met.

We know from studies done with endurance runners and vegetarians that diets very high in carbs can be very healthy in 
the long term. This assumes though that you get your carbs from quality sources.

If you exercice a lot and need the extra energy then you can consume large amounts of carbs as long as you get 
then from complex carbs and you also get your minimal protein and fat needs.

Also keep in mind that some people's stomach simply don't react well to a high carb diet. They will feel bloated and full 
and somewhat tired throughout the day. For all these people I recommend to keep the carb intake at the level in the last table and 
reach any other calories to health fats.


*** Dietary fats

Your body needs fatty acids to survive and cannot produce them from other foods.

Fat is needed to regulate hormone production, keep your skin and hair healthy, and
to absorb vitamins A, D, E and K (fat-soluble vitamins).

Fat cells insulate your body and help to keep you warm.

**** Types of Fat
There are two main types of fat:

- *Saturated fats* (eg. butter, cheese, whole milk) were long believed to raise LDL cholesterol level,
however recent studies suggest it's a lot less problematic. They are solid at room temperature.

- *Unsaturated fats* lower your LDL cholesterol level (include olive and canola oil, safflower, sunflower,
corn and soy oil).

There are also other types like *Trans fats*: form when vegetables oil is 
infused with hydrogen => avoid (eg. oil, butter and margarine) !


**** How much fat should you consume

Ideal Daily Fat Intake:
- 0.3 grams per pound of fat-free mass per day
- roughly 15 to 20% of daily calories 
- limit saturated fat intake, avoid artificial trans fats, and favor monounsaturated and polyunsaturated fats (unsaturated).

**** When to increase fat intake 

When all carbohydrates, fat and protein needs are already met, but your daily calories are not yet filled 
you have a choice to make => more proteinm fat or carbs?

In many cases, adding fat is good option because of:
- Taste
- Health effects
- Calorie density (9 cals vs 4) => ease of consumption
- Cost effectiveness


** Meal Timing  

*** Introduction

Even if meal planning has its importance, its effects are often overestimated.

*** Protein timing 

Even though the body can't store excess protein you don't have to eat 1 meal every 3 hours.

Our goal is to create a continual supply of amino acids.

The one variable we need to look at is protein digestion -> how fast or slow the consumed food is broken down into amino acids.

How long this process takes depends on three factors: 
- Protein type
  - Fastest digesting protein: whey (under 1 hour)
  - Medium: whole food proteins (several hours)
  - Slowest: dairy products (Up to & hours)
- Meal size
  - The simple addition of more food can prolong the digestion time of any protein source
  - Even more protein itself can delay absorption times
- Fat and fiber content
  - Bot fat and fiber will prolong the digestion of proteins to a considerable extent
  - A large, fatty steak can take as long to digest as a casein source
  

**** Meal frequency 

Your goal is to maintain a continual supply of amino acids to the muscle.

There are different ways of achieving this.

You can eat 6 smaller meals but you can also just eat 3 meals as long as they are large enough to cover both you daily protein needs
and are slowly digested.

**** Protein Timing and workout 

As long as you meet your daily calorie and nutritional requirements through your normal diet you don't have to drink a protein shake 
right before or after your workout. 

Instead get a =pre= and =post= meal right, which is something we will cover in a later lesson.

*** Carbohydrates timing 

**** Meal frequency 

With carbs meal frequency is not generally an issue unless you want or need to consume a lot.

You can again eat them in two or six meals throughout the day.

What's more important is that you time your carbs according to your workout schedule.

**** Carb timing and workout 

Eat some form of carbs before and after your workout.

Eating carbs before your workout will provide your muscles with additional fuel for your training, which will 
indirectly affect your muscle growth because it will help you train more intensively.

Eating carbs after your workout will refill glycogen stores which have been depleted.

Also including cabs in your post workout will quickly insulin levels and keep them elevated for a longer period of time. 
As mentioned earlier, insulin has anticatabolic properties which means it slows the rate of protein breakdown that occurs after 
the exercice.

**** Fat timing 

Fat timing is very simple. 

The only time you should avoid fats is right before your workout, since fat slows down the digestion of both carbs and proteins. 

Additionally, fat can be used to time meals over long intervals. This will maintain glucose and amino acids levels for a larger period of time.


** Pre workout meal

It's main function is to fuel the workout itself and maximize your performance.

In a scientific sense it's meant to do three things:
- Reduce muscle glycogen depletion 
- Reduce muscle protein breakdown
- Reduce post workout cortisol levels


*** Guidelines

Eat a balanced meal with 0.2 - 0.25g/lbs of your target bodyweight (for both carbs and proteins) up to one hour before your 
workout.

If your last meal lies more than two hours prior to your training, consume liquid or easily digested protein and carbs
30 minutes before your workout.

*** Suggestions

- Meals that you can eat up to 1 hour before your workout: 
  - Oatmeal with Whey Protein
  - Large chicken sandwich with wholegrain bread
  - 2x or more Hard-Boiled Eggs on an Avocado Toast 
  - Whole Grain pasta with some sort of protein

- Snacks 30 min or less before your workout:
  - Banana with whey protein shake
  - Apple wedges with cinnamon (and some light protein source)
  - Protein bar



** Post-Workout Meal

Meant to supply your body with everything it will need to repair the muscle tissue.
Specifically, the goal is to accomplish the following:

- Replenish muscle glycogen that was depelted during your workout
- Reduce muscle protein breakdown caused by exercice
- Increase muscle protein synthesis
- Reduce muscle soreness and fatigue
- Enhance overall recovery
- Reduce cortisol levels


Give your body the same macronutrients you did in the pre workout meal: Carbs and Protein (around 0.2 - 0.25g/lbs of your target bodyweight).

If you're really hungry you can increase the carbs.

Timing should be around 30-60 minutes after your workout.

Pre and post workout meals shouldn't be separated by more than 3-4 hours.

** What about the anabolic window
Studies have shown that under 60 min is still ok.


** Food composition

*** Introduction

Food composition will have a very minor impact on the goals. 

*** Protein Composition

*Bioavailability*: what percentage of the protein that you consume is actually absorbed into the bloodstream.

Another indicator of protein quality considers how much of the protein is composed of essential amino acids.
Obviously food that are high in essential amino acids are of high quality in this sense.

List of foods ranked by protein quality starting with the most quality sources:

- Whey Protein Isolate
- Whey Protein Concentrate
- Egg Sources (Cooked not raw)
- Meats (beef, pork)
- Poultry (chicken, turkey)
- Fish and seafood
- Soy protein and quinoa
- Combined plant sources (like beans and rice)
- Isolated plant sources (whole grain bread by itself, nuts by themselves)

BUT there is nothing worst for your physical and mental health than a one sided diet even though nuts for example aren't the highest quality proteins
they are a great source of fats and micronutrients. The same goes for other plant based sources of protein and fish and seafood.

*** Carbohydrate Composition

Just like protein composition, carbohydrate composition can refer to several concepts.

The most commom is the glycemic index which we already talked about in the lesson on the different types of carbs.

GI rankings are based on the glycemic effects of specific foods that are consumed isolated and fasted state.

Unless you have a pre-existing health condition, the human body is very good at keeping your blood sugar levels and insulin levels within a 
fairly precise range.

In real world scenarios, it really is not as important as mnany people make it out to be having your blood sugar or insulin levels increased
to higher than normal rate isn't going to have any major impact on muscle building or fat burning goals. Instead of comparing fast carbs and 
slow carbs, here is what you should focus on: 

Get the majority of your carb intake form high fiber, minimally processed source. This includes foods such as oatmeal, rice (brown or white),
potatoes, whole grain pasta, fruits and vegetables.

Consume your carbs as part of a complete meal with protein and healthy fats.

*** Fat Composition

For muscle building and fat burning, fat composition is even less important than protein and carbs composition.

Consuming certain kinds of fats and staying away from others will make a difference in your overall health.


| Fat type               | Recommended intake | Example foods                                                 |
|------------------------+--------------------+---------------------------------------------------------------|
| Monounsaturated        |                60% | Avocado, nuts and their butters, olive oil                    |
| Polyunsaturated        |                15% | Vegetable oils                                                |
| Healthy saturated      |                15% | Coconut/macadamia nut oils, grass fed animal fats             |
| Conventional saturated |                10% | Fats from conventionally farmed bacon, eggs, cheeses, butters |
| Trans                  |                 0% | Store-bought baked goods, most fast food                      |




** Supplements

Supplement can never replace proper diet planning and nutrition, but they can help you reach your fitness goals faster.

*** Protein powder

Even though you don't have to use protein powders to reach your recommended 
daily protein intake, consuming enough protein every day can be tricky. 

It most lokely won't matter all that much which kind of protein you buy as long as you take it regularly.

Optimal dosage: max. 30% - 50% of your daily protein intake.

*** Creatine

An organic acid that helps supply the muscle cells with energy for muscle cells during high-intensity, short duration exercice.

It also doesn't build muscle by itself, but it will increase your strength level.

Optimal dosage: 3-5 grams per day.

*** Fish Oil 

Boosts your mood, helps maintain healthy cholesterol levels and strong bones and ligaments.

Basically no side effects unless you are allergic to it.

Optimal dosage: 1000-3000mg of combied EPA/DHA per day.

*** How to use protein powder


**** Is a protein powder absolutely necessary to build muscle?

No.

As long as you reach your recommended daily protein intake you will be fine and see results.

However, consuming enough protein every day can be tricky, especially when you don't have time to prepare high protein meals all the time.

**** What time of protein powder is best?

There are a lot of protein powders you can buy (eg. whey, casein or egg).

As long as you don't get all your daily protein from supplements you won't notice the tiny differences among the different forms of protein.

Differeces in protein powder don't matter if rest of your diet is balanced enough to supply you with all essential amino acids.

**** When should you take protein powder?

Protein timing isn't really as important as people make it out to be.

Some studies show a positive effect on post workout protein on protein synthesis, while others find no such relation.

As long as you meet your daily calorie and nutritional requirements through your normal diet it doesn't matter when you take your 
protein shake.

**** How much protein powder shoul you take?

The majority of your diet should always be based on whole foods.

Depending on your lifestyle suggest you get around a third to half (maximum!) of your protein from protein shake.


**** What is the best liquid to mix protein powder with?

Water is ideal for any calorie restricted weight loss diet.

Milk will provide you some additional protein but also leads to a higher calorie count.

Other alternatives include soy or almond milk.


